forum/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ThreadList.as_view(), name='home'),
    path('thread', views.create_thread, name='thread'),
    path('follow/add/<int:thread_id>', views.follow_add, name='follow_add'),
    path('follow/', views.follow_list, name='follow_list'),
    path('<slug:slug>', views.thread_detail, name='thread_detail'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
]

stockrockets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("", include("forum.urls"), name="forum-urls"),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
import re

TOPICS = (
    (0, "News"),
    (1, "Strategies"),
    (2, "Analysis"),
    (3, "Economic"),
    (4, "Crypto"),
    (5, "Finance"),
    (6, "Education"),
)


# Create your models here.
# The model to create a new discussion thread
class Thread(models.Model):
    thread_id = models.AutoField(primary_key=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="thread_post"
    )
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    topic = models.IntegerField(choices=TOPICS, default=0)
    thread_text = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    follow = models.ManyToManyField(
        User, related_name='follow', default=None, blank=True)

    class Meta:
        ordering = ["-created_on"]

    def save(self):
        self.slug = self.title.lower().replace(" ", "-")
        # Remove special characters
        self.slug = re.sub(r'[^a-z0-9-]', '', self.slug)
        super().save()

    def __str__(self):
        return f"{self.title} | posted by {self.author}"


# The model to comment in a discussion thread
class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    thread = models.ForeignKey(
        Thread, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.body} | commented by {self.author}"

forum/forms.py
from django import forms
from .models import Comment, Thread, TOPICS


class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ['title', 'thread_text', 'topic']

    def __init__(self, *args, **kwargs):
        super(ThreadForm, self).__init__(*args, **kwargs)
        self.fields['topic'].widget.attrs.update({'class': 'form-select'})


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

forum/views.py
from django.shortcuts import (
    render, get_object_or_404, reverse, redirect, HttpResponseRedirect
)
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Thread, TOPICS, Comment
from .forms import CommentForm, ThreadForm


# This function requires the user to be logged in.
# It retrieves a list of threads followed by the current user.
# It renders a template displaying the profile page,
# and the list of followed threads.
@login_required
def follow_list(request):
    new = Thread.objects.filter(follow=request.user)
    return render(
        request,
        "forum/profile.html",
        {"new": new},
    )


# This function requires the user to be logged in.
# It allows users to add or remove threads from their followed list.
# It redirects the user back to previous page after the action is completed.
@login_required
def follow_add(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    if thread.follow.filter(id=request.user.pk).exists():
        thread.follow.remove(request.user)
        messages.add_message(request, messages.SUCCESS, 'Unfollowed thread!')
    else:
        thread.follow.add(request.user)
        messages.add_message(request, messages.SUCCESS, 'Followed thread!')
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


# This class-based view displays a list of threads based on the selected topic,
# or all threads if no topic is selected.
class ThreadList(generic.ListView):
    template_name = "forum/index.html"

    def get_queryset(self):
        topic_id = self.request.GET.get('topic', None)
        if topic_id is not None and topic_id != "":
            queryset = Thread.objects.filter(topic=topic_id)
        else:
            queryset = Thread.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topics'] = TOPICS
        context['thread_form'] = ThreadForm()
        return context


# This function requires the user to be logged in.
# It allows users to create a new thread.
# It renders the index page with a form to create a new thread.
@login_required
def create_thread(request):
    if request.method == "POST":
        thread_form = ThreadForm(data=request.POST)
        if thread_form.is_valid():
            thread = thread_form.save(commit=False)
            thread.author = request.user
            thread.save()
            messages.add_message(request, messages.SUCCESS,
                                 'YAY! You posted a new thread!')
            return redirect('thread_detail', slug=thread.slug)
        else:
            messages.info(request,
                          "There is some error with the details you provided. "
                          "Please retry.")

    else:  # For GET requests or invalid POST data
        thread_form = ThreadForm()

    return render(
        request,
        "forum/index.html",
        {
            'thread_form': thread_form,
            'topics': TOPICS,
            'thread_list': Thread.objects.all()
        },
    )


# This function displays details of a specific thread, including its comments.
# It also allows users to add comments to the thread.
def thread_detail(request, slug):
    queryset = Thread.objects.all()
    thread = get_object_or_404(queryset, slug=slug)
    comments = thread.comments.all().order_by("-created_on")
    comment_count = thread.comments.count()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.thread = thread
            comment.save()
            messages.success(request,
                             f"Comment '{comment.body}' created successfully!")
            return redirect('thread_detail', slug=comment.thread.slug)
        else:
            messages.error(request,
                           "Failed to create comment. Please try again!")

    comment_form = CommentForm()

    return render(
        request,
        "forum/thread_detail.html",
        {
            "thread": thread,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
        },
    )


# This function allows users to edit their comments on a thread.
def comment_edit(request, slug, comment_id):
    if request.method == "POST":
        queryset = Thread.objects.all()
        thread = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, comment_id=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.thread = thread
            comment.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Comment updated!')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating comment!')

    return HttpResponseRedirect(reverse('thread_detail', args=[slug]))


# This function allows users to delete their comments on a thread.
def comment_delete(request, slug, comment_id):
    queryset = Thread.objects.all()
    thread = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(request, messages.ERROR,
                             'You can only delete your own comments!')

    return redirect('thread_detail', slug=thread.slug)

forum/templates/forum/index.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- index.html content starts here -->
<div class="hero">
    <div>
        <img src="{% static 'images/stockrockets-header.png' %}" alt="Outerspace looking down over earth">
    </div>
    <div class="header-content">
        <h1>Welcome to StockRockets <i class="fa-solid fa-rocket"></i></h1>
    </div>
</div>
<div class="row">
    <!-- Topics -->
    <div class="col s12 m3">
        <div class="card-panel topic-collumn">
            <ul>
                <!-- "All Topics" button -->
                <li class="topics all-topic col s6 m12 l12">
                    <form method="GET" action="{% url 'home' %}">
                        <button type="submit" name="topic" value="" class="waves-effect waves-light btn-small custom-buttons">All Topics</button>
                    </form>
                </li>
                <!-- "Following" button -->
                <li class="topics all-topic col s6 m12 l12">
                    <form method="GET" {% if user.is_authenticated %}action="{% url 'follow_list' %}"{% else %}action="{% url 'account_login' %}"{% endif %}>
                        <button type="submit" name="topic" value="following" class="waves-effect waves-light btn-small custom-buttons">Following</button>
                    </form>
                </li>
            </ul>
            <hr class="col s12">
            <h5>Topics:</h5>
            <ul>
                {% for topic_id, topic_name in topics %}
                <li class="topics col s6 m12 l12">
                    <form method="GET" action="{% url 'home' %}">
                        <button type="submit" name="topic" value="{{ topic_id }}" class="waves-effect waves-light btn-small topic-buttons">{{ topic_name }}</button>
                    </form>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="col s12 m9 above-threads">
        <!-- New thread button -->
        <a class="waves-effect waves-light btn new-thread-btn modal-trigger" {% if user.is_authenticated %}href="#modal1"{% else %}href="{% url 'account_login' %}"{% endif %}>
            <i class="material-icons right">add_circle</i>
            start new discussion
        </a>
        <!-- New threads form in modal -->
        <div id="modal1" class="modal">
            <div class="modal-content">
                <h4>Create a new thread:</h4>
                <form method="post" action="/thread" id="thread-form">
                    {% csrf_token %}
                    {{ thread_form|crispy }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <!-- Threads -->
    <!-- Accsess the threadlist to use in JS with threads-container id-->
    <div class="col s12 m9" id="threads-container">
        <div class="card-panel">
            {% if thread_list %}
            {% for thread in thread_list %}
            <div class="thread-item">
                <div>
                    <div class="chip">
                        <img src="{% static 'images/anon-pp.png' %}" alt="Thread Author">
                        by {{thread.author}}
                    </div>
                    <a class="waves-effect waves-light btn-small topic-buttons right">{{thread.get_topic_display}}</a>
                </div>
                <ul class="collection">
                    <li class="collection-item">
                        {% if thread.slug %}
                        <a href="{% url 'thread_detail' thread.slug %}" class="thread-link">
                            <h5 class="heading">{{thread.title}}</h5>
                            <div class="card-text">{{ thread.thread_text |safe }}</div>
                        </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
            {% endfor %}
            {% else %}
            <p>No threads for that topic yet</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

forum/templates/forum/profile.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="col s12 m9" id="threads-container">
        <h1>Following threads:</h1>
        <div class="card-panel">
            {% if new %}
            {% for thread in new %}
            <div class="thread-item">
                <div>
                    <div class="chip">
                        <img src="{% static 'images/anon-pp.png' %}" alt="Thread Author">
                        by {{ thread.author }}
                    </div>
                    <a class="waves-effect waves-light btn-small topic-buttons right">{{ thread.get_topic_display }}</a>
                </div>
                <ul class="collection">
                    <li class="collection-item">
                        {% if thread.slug %}
                        <a href="{% url 'thread_detail' thread.slug %}" class="thread-link">
                            <h5 class="heading">{{ thread.title }}</h5>
                            <p class="card-text">{{ thread.thread_text | safe }}</p>
                        </a>
                        {% endif %}
                    </li>
                </ul>
                <form id="follow-form" action="{% url 'follow_add' thread.thread_id %}" method="POST">
                    <button class="btn unfollow-btn waves-effect waves-light" type="submit" name="follow_add">Unfollow
                        Thread</button>
                    {% csrf_token %}
                </form>
            </div>
            {% endfor %}
            {% else %}
            <p>You are not following any threads</p>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

forum/templates/forum/thread_detail.html
{% extends 'base.html' %} 
{% block content %}

{% load static %}
{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <div class="created-info">
                    <div class="chip">
                        <img src="{% static 'images/anon-pp.png' %}" alt="Thread Author">
                        by {{thread.author}}
                    </div>
                    <p> | {{ thread.created_on }}</p>
                    <a class="waves-effect waves-light btn-small topic-buttons right">{{thread.get_topic_display}}</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% if user.is_authenticated %}
<div class="container" id="follow-btn">
    <form id="follow-form" action="{% url 'follow_add' thread.thread_id %}" method="POST">
        <button class="btn waves-effect waves-light" type="submit" name="follow_add">Follow Thread</button>
        {% csrf_token %}
    </form>
</div>
{% else %}
<div class="container" id="follow-btn">
    <a class="teal lighten-4" href="{% url 'account_login' %}">Login</a> to follow thread
</div>
{% endif %}

<div class="container">
    <div class="row">
        <div id="thread-text-card" class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <h3 class="post-title">{{ thread.title }}</h3>
                <div class="card-text">{{ thread.thread_text | safe }}</div>
            </div>
        </div>
    </div>
</div>

<!-- Displaying Comments -->
<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <strong>
                    <i class="far fa-comments" id="comment_count"></i> {{ comment_count }}
                </strong> 
                <div class="col-12">
                    <hr>
                </div>
                <!-- Comment form -->
                <div class="col-md-4 mb-4 mt-3">
                    {% if user.is_authenticated %}
                    <h4 class="comment-heading">Leave a comment:</h4>
                    <p>Posting as: {{ user.username }}</p>
                    <form id="commentForm" method="post" style="margin-top: 1.3em;">
                        {{ comment_form | crispy }}
                        {% csrf_token %}
                        <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
                    </form>
                    {% else %}
                    <p><a class="teal lighten-4" href="{% url 'account_login' %}">Login</a> to leave a comment</p>
                    {% endif %}
                </div>
                <h4 class="comment-heading"> Comments: </h4>
                {% for comment in comments %}
                <div class="created-info">
                    <div class="col card mb-4  mt-3 left  top">
                        <div class="card-body">
                            <div class="created-info">
                                <div class="chip">
                                    <img src="{% static 'images/anon-pp.png' %}" alt="Comment Author">
                                    by {{ comment.author }}
                                </div>
                                <p>{{ comment.created_on }}</p>
                            </div>
                            <p id="comment{{ comment.comment_id }}" class="card-text">{{ comment.body | safe }}</p>
                            {% if request.user == comment.author %}
                            <button data-target="deleteModal" class="btn btn-delete modal-trigger" comment_id="{{ comment.comment_id }}">Delete</button>
                            <button class="btn btn-edit" comment_id="{{ comment.comment_id }}" data-slug="{{ thread.slug }}">Edit</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        
    </div>
</div>
<!-- Delete confirmation modal -->
<div id="deleteModal" class="modal">
    <div class="modal-content">
      <h4>Are you sure you want to delete your comment?</h4>
    </div>
    <div class="modal-footer">
        <form id="deleteConfirm">
            <button type="button" class="btn btn-secondary modal-close" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>


{% endblock content %}

{% block extras %}
<script>
    let thread_slug = `{{ thread.slug }}`
</script>
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}